site_name: Beágyazott operációs rendszerek és kliens alkalmazások
site_author: Benedek Zoltán
copyright: Copyright &copy; BME VIK AUT
repo_name: bmeviauac14/borka
repo_url: https://github.com/bmeviauac14/borka

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  language: hu
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: aut
      primary: aut
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Váltás sötét témára
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/lightbulb
        name: Váltás világos témára
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - search.suggest
    - content.action.edit
  logo: img/logo-bme-aut.png
  favicon: img/favicon.ico

extra_css:
  - extra-material-theme.css

extra:
  generator: false

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list


plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: false
      type: timeago
      timezone: Europe/Budapest
      locale: hu
  - git-committers:
      repository: bmeviauac14/borka
      branch: main

nav:
  - index.md
  - "Gyakorlatok":
      - gyakorlat/nyelvi-eszkozok/index.md
      - gyakorlat/felhasznaloi-felulet/index.md
      - gyakorlat/tobbszalu/index.md
      - gyakorlat/doc-view/index.md    
  - "Önálló/házi feladatok":
      - 'Útmutató': hazi/index.md
